services:
  db:
    image: postgres:16
    container_name: postgres_app
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.0
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command:
      - start-dev
      - --import-realm
      - --hostname-strict=false
      - --proxy-headers=xforwarded
      - --http-relative-path=/auth
      - --spi-hostname-default-frontend-url=https://localhost/auth
      - --spi-hostname-default-backend-url=http://keycloak:8080/auth
    ports:
      - "8080:8080"  # only for dev env use
    volumes:
      - ./keycloak-config:/opt/keycloak/data/import
    restart: always

  nginx:
    build: ./nginx 
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/certs:/certs 
    depends_on:
      - angular
      - backend
      - keycloak

  backend:
    build: ./backend
    container_name: spring_backend
    environment:
      DB_HOST: db
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      KEYCLOAK_ISSUER_URI: https://localhost/auth/realms/health-realm
      KEYCLOAK_JWKS_URI: http://keycloak:8080/auth/realms/health-realm/protocol/openid-connect/certs

    depends_on:
      - db
      - keycloak
    ports:
      - "8081:8081"

  angular:
    image: node:20
    container_name: angular_frontend
    working_dir: /usr/src/app
    ports:
      - "4200:4200"
    environment:
      BACKEND_URL: https://localhost/api
      KEYCLOAK_URL: https://localhost/auth
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: >
      sh -c "npm install &&
             npm run start -- --host 0.0.0.0 --disable-host-check"
    depends_on:
      - backend
      - keycloak

volumes:
  db_data:
  keycloak_data: