server:
  port: 8081 # We picked 8081 to avoid clashing with Keycloak (which uses 8080).
  address: 0.0.0.0


spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${POSTGRES_DB:mydb}
    username: ${POSTGRES_USER:app}
    password: ${POSTGRES_PASSWORD:app}

  jpa:
    hibernate:
      ddl-auto: update

# Every request to this backend must include a JWT issued by this Keycloak realm, and I should validate it using that realm’s public keys
# A realm is simply a separate security space inside Keycloak. Each realm has its own users, roles, login settings, and applications. Nothing in one realm affects another
  security: 
    oauth2:
      resourceserver:
        jwt:
          # Trust JWT access tokens that come from this Keycloak realm.
          issuer-uri: ${KEYCLOAK_ISSUER_URI:https://localhost/auth/realms/health-realm}
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:https://localhost/auth/realms/health-realm/protocol/openid-connect/certs}



